import Head from "next/head";
import MyForm from "@/components/Form";
import { useAccount, useConnect } from "wagmi";
import { InjectedConnector } from "wagmi/connectors/injected";
import { useState, useEffect } from "react";

export default function Home() {
  const { isConnected } = useAccount();
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });
  const [isReady, setIsReady] = useState(false);

  useEffect(() => setIsReady(true), []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isReady && (
        <main
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            height: "100vh",
            backgroundColor: "#000",
          }}
        >
          {!isConnected ? (
            <button onClick={() => connect()} id="connect-btn">
              Connect Wallet
            </button>
          ) : (
            <MyForm />
          )}
        </main>
      )}
    </>
  );
}
